name: Nintendont Build

on: [push, pull_request]

jobs:
  build:
    name: Build Nintendont
    runs-on: ubuntu-20.04
    container: devkitpro/devkitppc:latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build Nintendont dol
      run: |
        make -j2

    - name: Copy Nintendont artifacts
      run: | 
        mkdir -p dist/Nintendont/apps/Nintendont
        cp nintendont/icon.png dist/Nintendont/apps/Nintendont/
        cp nintendont/meta.xml dist/Nintendont/apps/Nintendont/
        cp loader/loader.dol dist/Nintendont/apps/Nintendont/boot.dol

    - name: Upload Nintendont artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: Nintendont
        path: |
         dist/Nintendont/
