name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Compile Nintendont
      uses: ./.github/actions
    - name: Commit loader.dol
      run: |
        git config user.name '${{ github.actor }}'
        git config user.email '${{ github.actor }}@users.noreply.github.com'
        git add loader/loader.dol
        ( git commit -m "loader.dol" && git push ) || true
    - uses: actions/upload-artifact@v1
      with: 
        name: Nintendont
        path: build/
